//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GostinicaEntities4 : DbContext
    {
        private static GostinicaEntities4 _context;
        public GostinicaEntities4()
            : base("name=GostinicaEntities4")
        {
        }

        public static GostinicaEntities4 GetContext()
        {
            if (_context == null)
                _context = new GostinicaEntities4();

            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doljnosti> Doljnostis { get; set; }
        public virtual DbSet<Kategorii> Kategoriis { get; set; }
        public virtual DbSet<Klient> Klients { get; set; }
        public virtual DbSet<Nomera> Nomeras { get; set; }
        public virtual DbSet<Operacii> Operaciis { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudnikis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Uchet> Uchets { get; set; }
    }
}
