//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomera
    {
        public int ID_nomera { get; set; }
        public Nullable<int> Nomer__ { get; set; }
        public Nullable<decimal> Stoimost_v_sutki { get; set; }
        public Nullable<int> Kolichestvo_mest { get; set; }
        public Nullable<int> ID_kategorii { get; set; }
    
        public virtual Kategorii Kategorii { get; set; }
    }
}
