//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GostinicaEntities3 : DbContext
    {
        public static GostinicaEntities3 _context;
        public GostinicaEntities3()
            : base("name=GostinicaEntities3")
        {
        }
    
        public static GostinicaEntities3 GetContext()
        {
            if (_context == null)
                _context = new GostinicaEntities3();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sotrudniki> Sotrudnikis { get; set; }
        public virtual DbSet<Doljnosti> Doljnostis { get; set; }
    }
}
