//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int ID_sotrudnika { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> ID_doljnosti { get; set; }
    
        public virtual Doljnosti Doljnosti { get; set; }
    }
}
