//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchet
    {
        public int ID_ucheta { get; set; }
        public Nullable<int> ID_operacii { get; set; }
        public Nullable<int> ID_nomera { get; set; }
        public Nullable<int> ID_klienta { get; set; }
        public Nullable<System.DateTime> Date_vezda { get; set; }
        public Nullable<System.DateTime> Date_viezda { get; set; }
        public Nullable<decimal> Stoimost { get; set; }
        public Nullable<int> ID_sotrudnika { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Nomera Nomera { get; set; }
        public virtual Operacii Operacii { get; set; }
        public virtual Sotrudniki Sotrudniki { get; set; }
    }
}
